name: Build opencore-amr from tarball

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool build-essential

      - name: Extract and build
        run: |
          tar xf opencore-amr-0.1.6.tar.gz
          cd opencore-amr-0.1.6
          ./configure --enable-static --disable-shared --enable-amrnb
          make -j$(nproc)
          mkdir -p ../artifacts/linux
          cp amrnb/.libs/libopencore-amrnb.a ../artifacts/linux/
          cp amrnb/interf_dec.h ../artifacts/linux/
          cp amrnb/interf_enc.h ../artifacts/linux/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain

      - name: Extract and build
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm autoconf automake libtool
          tar xf opencore-amr-0.1.6.tar.gz
          cd opencore-amr-0.1.6
          ./configure --host=mingw32 --enable-static --disable-shared --enable-amrnb
          make -j$(nproc)
          mkdir -p ../artifacts/windows
          cp amrnb/.libs/libopencore-amrnb.a ../artifacts/windows/
          cp amrnb/interf_dec.h ../artifacts/windows/
          cp amrnb/interf_enc.h ../artifacts/windows/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install autoconf automake libtool

      - name: Extract and build
        run: |
          tar xf opencore-amr-0.1.6.tar.gz
          cd opencore-amr-0.1.6
          ./configure --enable-static --disable-shared --enable-amrnb
          make -j$(sysctl -n hw.logicalcpu)
          mkdir -p ../artifacts/macos
          cp amrnb/.libs/libopencore-amrnb.a ../artifacts/macos/
          cp amrnb/interf_dec.h ../artifacts/macos/
          cp amrnb/interf_enc.h ../artifacts/macos/

   upload:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload compiled artifacts
        uses: actions/upload-artifact@v3
        with:
          name: opencore-amr-libs
          path: artifacts/
